## Disable output (sink) nodes for devices used exclusively as inputs.

monitor.alsa.rules = [
  {
    matches = [
      { node.name = "alsa_output.pci-0000_03_00.1.hdmi-stereo" }
    ]
    actions = { update-props = { node.disabled = true } }
  }
  {
    matches = [
      { node.name = "alsa_output.usb-Focusrite_Scarlett_Solo_USB_Y7DXGVU11B875C-00.pro-output-0" }
    ]
    actions = { update-props = { node.disabled = true } }
  }
]
